name: 10A1-SMP-Scoreboard
version: 1.0.0
main: com.smp10a1.scoreboard.Main
api-version: '1.26'
author: Admin10A1
description: Plugin hien thi bang thong tin tinh gian cho 10A1 SMP tren phien ban 1.26.20
